media: src/assets
content: 
  - name: docs
    label: Docs
    type: collection
    path: 'src/content/docs'
    view:
      fields: [ title, published ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text 